{
    "message": "请求成功",
    "status": "200",
    "data": {
        "activityDesc": "<link rel=\"stylesheet\" href=\"css/huodong.css\"><div id=\"activityDesc_html\"><div id=\"activity_desc\"><div id=\"activity_desc_title\" class=\"act_title\"><p><img src=\"http://7xavon.com1.z0.glb.clouddn.com/sanjiao1463993854.png\"><span>活动描述</span></p></div><div id=\"activity_desc_html\"><p class=\"activity_desc_html_content\">活动描述活动描述活动描述活动描述活动描述活动描述活动描述<br>活动描述活动描述活动描述活动描述</p></div></div><div id=\"activity_prize\"><div id=\"activity_prize_title\" class=\"act_title\"><p><img src=\"http://7xavon.com1.z0.glb.clouddn.com/sanjiao1463993854.png\"><span>奖项</span></p></div><div class=\"itemlist\" onclick=\"openUrl('http://git.oschina.net/progit/')\"><div class=\"item_prize\"><div class=\"item_prize_img\"><img src=\"http://7xavon.com1.z0.glb.clouddn.com/FnqJETJPeKPXbDfqXqy8NrV9sKN7\"></div><div class=\"item_prize_info\"><p class=\"item_prize_type\">创意奖</p><p class=\"item_prize_title\">Rainbow Pencils 彩虹铅笔Rainbow Pencils 彩虹铅笔Rainbow Pencils 彩虹铅笔Rainbow Pencils 彩虹铅笔</p></div><div class=\"item_arrow\"><img src=\"http://7xavon.com1.z0.glb.clouddn.com/goon_btn1464000995.png\"></div></div><div style=\"clear:both;\"></div></div><div class=\"itemlist\" onclick=\"openUrl('http://git.oschina.net/progit/')\"><div class=\"item_prize\"><div class=\"item_prize_img\"><img src=\"http://7xavon.com1.z0.glb.clouddn.com/Fs8Esu0-cud8d_qBcA837Mt9HYHb\"></div><div class=\"item_prize_info\"><p class=\"item_prize_type\">人气奖</p><p class=\"item_prize_title\">牛头梗 抱枕</p></div><div class=\"item_arrow\"><img src=\"http://7xavon.com1.z0.glb.clouddn.com/goon_btn1464000995.png\"></div></div><div style=\"clear:both;\"></div></div><div class=\"itemlist\" onclick=\"openUrl('http://git.oschina.net/progit/')\"><div class=\"item_prize\"><div class=\"item_prize_img\"><img src=\"http://7xavon.com1.z0.glb.clouddn.com/FtTxYY3GtabEZeTXmxjTtkj1cOBi\"></div><div class=\"item_prize_info\"><p class=\"item_prize_type\">任性奖</p><p class=\"item_prize_title\">züny 法国斗牛犬摆件</p></div><div class=\"item_arrow\"><img src=\"http://7xavon.com1.z0.glb.clouddn.com/goon_btn1464000995.png\"></div></div><div style=\"clear:both;\"></div></div></div><div id=\"activity_mingdan\"><div id=\"activity_mingdan_title\" class=\"act_title\"><p><img src=\"http://7xavon.com1.z0.glb.clouddn.com/sanjiao1463993854.png\"><span>上期名单</span></p></div><div id=\"activity_mingdan_url\"><a href=\"https://www.baidu.com/\" target=\"_self\"><p><span>点击查看</span><img src=\"http://7xavon.com1.z0.glb.clouddn.com/mingdan_btn1464060262.png\"> 另一种视野——遇见不一样的生活</p></a></div></div></div>",
        "activityDescUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fu9GTxVYbboZQFbJrBNFVmI16aRj",
        "activityPrize": "艺术狗（Artgoer），是由杭州艺藏文化艺术有限公司开发的国内首款移动互联网在线看展APP产品，汇聚全球最优质的艺术展览，将线下展出作品如数在互联网移动端展示，让用户可以足不出户，看遍艺术展览。[3] 与此同时，用户还可在线看到艺术达人的点评，与艺术达人在线交流，并对每一幅作品发表自己的见解和看法。 艺术狗（Artgoer）最大程度地将艺术机构和线下展览推向了艺术爱好者，让艺术圈内和圈外发生最大程度的连结关系，让在线看展成为移动互联网时代人们的一种生活方式。",
        "activityPrizeUrl": "http://7xavon.com1.z0.glb.clouddn.com/FjPk2i-IirJ9x0pRXC9LX18hZarv",
        "activityVoteSum": 24871,
        "activityWorks": [
            {
                "activityId": 41,
                "address": "15826473396",
                "id": 8109,
                "mobile": "15826473396",
                "userId": 113140,
                "userName": "费费",
                "voteNum": 9601,
                "worksName": "《青蛇》徐克1993 ",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fg-BoILjuo5XaOFSDRtvPK7bQPSb"
            },
            {
                "activityId": 41,
                "address": "17733121249",
                "id": 8057,
                "mobile": "17733121249",
                "userId": 146325,
                "userName": "Y",
                "voteNum": 3588,
                "worksName": "曾有公子世无双",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FkxykaZSoR3qnyDFNxsM5hzFM2wd"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8050,
                "mobile": "",
                "userId": 33524,
                "userName": "CC",
                "voteNum": 1336,
                "worksName": "一天",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FjRc-e46xvU13BOrjC1p8koYRRPg"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8052,
                "mobile": "",
                "userId": 33524,
                "userName": "CC",
                "voteNum": 1156,
                "worksName": "泰坦尼克号",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FpMaYuYvsOrZXM7mMnQezWAjkViy"
            },
            {
                "activityId": 41,
                "address": "15987121529",
                "id": 8066,
                "mobile": "15987121529",
                "userId": 184230,
                "userName": "ことなみ.",
                "voteNum": 880,
                "worksName": "哈利波特",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Flcs7ztGZbh45gF3Qbwt-KLnigeZ"
            },
            {
                "activityId": 41,
                "address": "13456895642",
                "id": 8135,
                "mobile": "13456895642",
                "userId": 180809,
                "userName": "夏大雨",
                "voteNum": 790,
                "worksName": "1997 美丽人生 最爱的电影，没有之一。",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fs6o1bXnyi_ZsUwr69AHtsbi_pfi"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8055,
                "mobile": "",
                "userId": 33524,
                "userName": "CC",
                "voteNum": 732,
                "worksName": "披头士",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FgowiQ7WZYq9EzjWpgR8TxloYxoh"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8074,
                "mobile": "",
                "userId": 33524,
                "userName": "CC",
                "voteNum": 692,
                "worksName": "罗马假日",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fi1y3m7-IKszsoaTfS0_Y9HQGQsa"
            },
            {
                "activityId": 41,
                "address": "15987121529",
                "id": 8067,
                "mobile": "15987121529",
                "userId": 184230,
                "userName": "ことなみ.",
                "voteNum": 621,
                "worksName": "星空",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FmdXh42XO500HLS4Vhpz6TjLBEkP"
            },
            {
                "activityId": 41,
                "address": "15987121529",
                "id": 8069,
                "mobile": "15987121529",
                "userId": 184230,
                "userName": "ことなみ.",
                "voteNum": 617,
                "worksName": "三印异兽",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FuE-4kC5hsQsqBye7ZVP7L2dK1rZ"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8647,
                "mobile": "",
                "userId": 191598,
                "userName": "水一方",
                "voteNum": 605,
                "worksName": "90年代初记忆",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FiZRqf91fku3gMMzlR2x5fU4t3Gn"
            },
            {
                "activityId": 41,
                "address": "18719039422",
                "id": 8107,
                "mobile": "18719039422",
                "userId": 174258,
                "userName": "釉绿小室",
                "voteNum": 580,
                "worksName": "98年集市上淘来的一直挂在老家客厅",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FoLAiCeqjfneTvGFhwxqEpOH-jG2"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8073,
                "mobile": "",
                "userId": 33524,
                "userName": "CC",
                "voteNum": 524,
                "worksName": "蒂凡尼的早餐",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Ftt-mJNq0cZ1LvzckjUMpujxe0S8"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8075,
                "mobile": "",
                "userId": 33524,
                "userName": "CC",
                "voteNum": 497,
                "worksName": "蓝桥断魂",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FqG24YECvyeDgkgPncy9Y9jUvXF3"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8072,
                "mobile": "",
                "userId": 33524,
                "userName": "CC",
                "voteNum": 376,
                "worksName": "断背山",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FrMfIQV0K037bkAypeaY32zTUmpN"
            },
            {
                "activityId": 41,
                "address": "13941387669",
                "id": 8084,
                "mobile": "13941387669",
                "userId": 114681,
                "userName": "luooer",
                "voteNum": 147,
                "worksName": "1997年",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fh5iegy0BBu8_KxtcB_oOaHiGC62"
            },
            {
                "activityId": 41,
                "address": "13941387669",
                "id": 8088,
                "mobile": "13941387669",
                "userId": 114681,
                "userName": "罗格",
                "voteNum": 130,
                "worksName": "《游园惊梦》梅兰芳 1960",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FhDKw9tmeVIxdF0RwSxZfm7yStR0"
            },
            {
                "activityId": 41,
                "address": "13941387669",
                "id": 8099,
                "mobile": "13941387669",
                "userId": 114681,
                "userName": "luooer",
                "voteNum": 117,
                "worksName": "《摩登时代》1936",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FnwCb4KfHpXXYAnTKS0owHGKYB3M"
            },
            {
                "activityId": 41,
                "address": "13941387669",
                "id": 8087,
                "mobile": "13941387669",
                "userId": 114681,
                "userName": "戈德",
                "voteNum": 115,
                "worksName": "1997",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FkU7BIrx-tH8_PWpQwClkwiXmNwo"
            },
            {
                "activityId": 41,
                "address": "13941387669",
                "id": 8090,
                "mobile": "13941387669",
                "userId": 114681,
                "userName": "洛奇",
                "voteNum": 111,
                "worksName": "2014",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FsinVYjTFHrmoLCc0LgI9clggiMD"
            }
        ],
        "createDate": "2016-04-19 17:35:29",
        "endDate": "2016-04-27 18:00:00",
        "id": 41,
        "isEnterFor": "2",
        "newActivityWorks": [
            {
                "activityId": 41,
                "address": "",
                "id": 9196,
                "mobile": "",
                "userId": 33524,
                "userName": "CC",
                "voteNum": 1,
                "worksName": "艺术狗保存",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FvQR6yOyE9PTg353-wqHBbFrfJkj"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 9189,
                "mobile": "",
                "userId": 198258,
                "userName": "HUAZEHE",
                "voteNum": 0,
                "worksName": "",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FqOLwK6x4EzajG_3LvpJFw_9YPWa"
            },
            {
                "activityId": 41,
                "address": "17839216718",
                "id": 9186,
                "mobile": "17839216718",
                "userId": 198215,
                "userName": "～不疯魔不成活——",
                "voteNum": 0,
                "worksName": "永远的罗马",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fr-Az65681K_kZEKQJBWHiUeuVd5"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 9185,
                "mobile": "",
                "userId": 198215,
                "userName": "～不疯魔不成活——",
                "voteNum": 0,
                "worksName": "",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FlOqd6Rx9iHfwbbAS9n7un4hgQ56"
            },
            {
                "activityId": 41,
                "address": "18687619150",
                "id": 9162,
                "mobile": "18687619150",
                "userId": 195393,
                "userName": "波波波",
                "voteNum": 0,
                "worksName": "东京爱情故事",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FrPq4K8KbBQtVqswSCj0VysmOzOr"
            },
            {
                "activityId": 41,
                "address": "18313740904",
                "id": 9161,
                "mobile": "18313740904",
                "userId": 198088,
                "userName": "三石",
                "voteNum": 0,
                "worksName": "大叔和萝莉",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FscLXc9l2PWQDq4MwUTL5BSGb4--"
            },
            {
                "activityId": 41,
                "address": "13047049531",
                "id": 9153,
                "mobile": "13047049531",
                "userId": 120193,
                "userName": "“吃西瓜”",
                "voteNum": 2,
                "worksName": "1994.夜访吸血鬼",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FmMpSgMQC-gAe_Q8gNa2s2p-mfSY"
            },
            {
                "activityId": 41,
                "address": "15066839039",
                "id": 9152,
                "mobile": "15066839039",
                "userId": 184126,
                "userName": "轻舞飞扬",
                "voteNum": 0,
                "worksName": "《小兵张嘎》旧时光的美好回忆",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fk3ddTqT1FD8dD2NiKG7zqizU6p7"
            },
            {
                "activityId": 41,
                "address": "15155111679",
                "id": 9128,
                "mobile": "15155111679",
                "userId": 197400,
                "userName": "Nika.",
                "voteNum": 0,
                "worksName": "社会主义的一路下来。",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fp_j1iw6_3WNY8H7VTOC-kTr1sUQ"
            },
            {
                "activityId": 41,
                "address": "15696151020",
                "id": 9084,
                "mobile": "15696151020",
                "userId": 196433,
                "userName": "泡菜坛子酸豇豆",
                "voteNum": 0,
                "worksName": "每个人心中都有一个江湖梦",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FiwTiIAgN9rEduAN6RvLBLbixg69"
            },
            {
                "activityId": 41,
                "address": "18280150041",
                "id": 9048,
                "mobile": "18280150041",
                "userId": 196988,
                "userName": "planning",
                "voteNum": 1,
                "worksName": "1997 happy together",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fm3iaoP4HyrArPQip9zu8fmKCBse"
            },
            {
                "activityId": 41,
                "address": "13425133382",
                "id": 9045,
                "mobile": "13425133382",
                "userId": 196485,
                "userName": "viki--wang",
                "voteNum": 0,
                "worksName": "猛龙过江",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FsxdbQhXkcEnArftb2PZLdJHpxrX"
            },
            {
                "activityId": 41,
                "address": "13435070042",
                "id": 9033,
                "mobile": "13435070042",
                "userId": 103103,
                "userName": "敢达小华哥",
                "voteNum": 0,
                "worksName": "《新垣结衣》——梦里的人",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FnQHbane0ATDnsFT1b3HB6JiINSl"
            },
            {
                "activityId": 41,
                "address": "13435070042",
                "id": 9032,
                "mobile": "13435070042",
                "userId": 103103,
                "userName": "敢达小华哥",
                "voteNum": 0,
                "worksName": "《教父》——一代人的巅峰 几代人的经典",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FudKQXjsJbL9Nld2riYsxq1CzGFe"
            },
            {
                "activityId": 41,
                "address": "18371122613",
                "id": 9031,
                "mobile": "18371122613",
                "userId": 184873,
                "userName": "且听风吟",
                "voteNum": 58,
                "worksName": "同名",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FoUBgqUZ0pLeeBj7VPWNlcWH_Pa8"
            },
            {
                "activityId": 41,
                "address": "15874981669",
                "id": 9018,
                "mobile": "15874981669",
                "userId": 143651,
                "userName": "董只-",
                "voteNum": 0,
                "worksName": "2008年 步履不停",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FpwNZ9WRaxdlQptFsQI0mw8kjfda"
            },
            {
                "activityId": 41,
                "address": "13979322221",
                "id": 8988,
                "mobile": "13979322221",
                "userId": 196495,
                "userName": "玲",
                "voteNum": 0,
                "worksName": "花样年华 2000年出品",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FnKD4cKjHclOKMdrXoYlEhmMZnuB"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8984,
                "mobile": "",
                "userId": 189055,
                "userName": "赫本女神",
                "voteNum": 0,
                "worksName": "",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fl91I5iqnNARCVS4ZorulnZY_yfp"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8976,
                "mobile": "",
                "userId": 41363,
                "userName": "小茗同学",
                "voteNum": 0,
                "worksName": "伊冠有礼音乐时代",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FpJRusmMMHiutJ6IkiEJQDAcqK9Y"
            },
            {
                "activityId": 41,
                "address": "",
                "id": 8952,
                "mobile": "",
                "userId": 195105,
                "userName": "行云流水",
                "voteNum": 1,
                "worksName": "如诗如你",
                "worksPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FkKs5MtjfOv9rKHtAGTkgm1MddLM"
            }
        ],
        "startDate": "2016-04-19 18:00:00",
        "subject": "海报—旧时光里的风情",
        "subjectUrl": "http://7xavon.com1.z0.glb.clouddn.com/FvzHfeZf9ibtLz4YGAfXZBayOsM7",
        "updateDate": "2016-05-27 09:55:24"
    }
}
