{
  "data": {
    "commentList": [
      {
        "columnId": 0,
        "commentTxt": "耶耶耶",
        "createAt": "2015-12-28 16:26:39",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6722,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9824,
        "userName": "AB型的鸡腿君",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FthRu8MWdwub6MmBfEgKzWSy5LUI",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "银华基金好",
        "createAt": "2015-12-01 14:21:50",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6440,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9819,
        "userName": "岚",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FnzLhapIbEpDhdNWFgO1f6U9yvj-",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "发几个好不急不急",
        "createAt": "2015-12-01 11:56:47",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6432,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9819,
        "userName": "岚",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FnzLhapIbEpDhdNWFgO1f6U9yvj-",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "耶耶耶耶耶一样一样一样一样一样一样一样一样一样一样一样一样一样一样一样一样一样一样鱼鱼鱼鱼鱼鱼鱼鱼鱼鱼鱼\n哈哈哈发大地飞歌v",
        "createAt": "2015-12-01 15:35:58",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6444,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 2690,
        "userName": "zjandxn",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FutsrZhMuDbA52AiWKHz9za3t-0y",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "啦啦啦啦",
        "createAt": "2015-12-17 11:20:31",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6605,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9810,
        "userName": "testing",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FmfyL2udOFo8CgviU2KeL-SbZGDN",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "好vv好v计划计划合肥公交就给个机会i好看看好u复分解干活吧就回家距聚聚",
        "createAt": "2015-12-01 11:32:16",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6422,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9819,
        "userName": "岚",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FnzLhapIbEpDhdNWFgO1f6U9yvj-",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "古u姑姑家感激不尽",
        "createAt": "2015-12-01 14:09:20",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6437,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9819,
        "userName": "岚",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FnzLhapIbEpDhdNWFgO1f6U9yvj-",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "公积金刚刚和价格举报",
        "createAt": "2015-12-01 14:09:33",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6439,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9819,
        "userName": "岚",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FnzLhapIbEpDhdNWFgO1f6U9yvj-",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "啊说了肯德基阿拉斯加多久啊时爱仕达爱斯卡达",
        "createAt": "2015-11-30 11:09:41",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6378,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9848,
        "userName": "快乐的小建",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/Fu_qqkdFCEI__RT8Hmh1Nsqg7yfQ",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "啊数据库等哈说",
        "createAt": "2015-11-30 11:11:19",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 6381,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9816,
        "userName": "情况不明啦啦啦啦啦啦啦啦啦啦",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FtNaEmbbCCdjxAW-Dr1zY1lkArFM",
        "verifyStatus": 0,
        "workId": 0
      }
    ],
    "topic": {
      "author": "情况不明啦啦啦啦啦啦啦啦啦啦",
      "createAt": "2015-11-30 00:00:00",
      "headPic": "http://7xavon.com1.z0.glb.clouddn.com/FtNaEmbbCCdjxAW-Dr1zY1lkArFM",
      "id": 63,
      "isDeleted": 0,
      "isEnterfor": 0,
      "joinNum": 3,
      "marketingDeschtml": "<p>徐震以惯有的幽默姿态介入有关全球文化的各种议题，充满张力的表达将西方精神与东方文化巧妙地结合，一种超越传统范式的新文化在此诞生。全新创作的《欧洲千手古典雕塑》集合19座不同形态的西方古典雕塑，借佛像中千手观音之形，兼顾形式感与精神性，呈现出一种蓬勃的生命力，震撼观众的视觉。《永生》嫁接东方庄严静穆的佛像与希腊典雅精致的雕像，贯通广袤的时间和空间，指涉令人敬畏的艺术史，显示东方智慧的包容。《永生-双人头部支撑单手平衡雕塑》拼接两座西方雕塑，荒诞又触动神经的视觉效果完美体现力量与信念的平衡。《没顶曲项瓶》将中国经典古瓷的脖颈旋转九十度，成就陶瓷史最伟大动作。《意识形状博物馆》以社会、宗教和传统的范式为元素，发明了一套世界首创的心灵健身操。《金属的语言》收集漫画中的文字，用金属链条拼绘出独立而鲜活的短句，充分展现思想的质感。而《天下》新推出“黑光”系列，黑色的“奶油”丛林广袤深邃，散发出浓郁神秘气息，无畏无惧的力量喷薄而出。</p>",
      "showTopicHead": "0",
      "topicHeadType": 0,
      "topicName": "你妈是怎么爱你的你妈是怎么爱你的你妈是怎么爱你的",
      "topicType": 0,
      "userId": 9816,
      "viewerNum": 0
    }
  },
  "message": "请求成功",
  "status": "200"
}
