{
  "data": {
    "commentList": [
      {
        "columnId": 0,
        "commentTxt": "去阿姣",
        "createAt": "2016-02-25 18:09:27",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 7442,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9816,
        "userName": "情况不明啦啦啦啦啦啦啦啦啦啦",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/FtNaEmbbCCdjxAW-Dr1zY1lkArFM",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "v 黄金美女健健康康",
        "createAt": "2016-02-25 18:10:11",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 7444,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9864,
        "userName": "新账号！",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/Frn9Da1fkFgXQW8NgeAhs2xpVxvd",
        "verifyStatus": 0,
        "workId": 0
      },
      {
        "columnId": 0,
        "commentTxt": "v 被你们看看",
        "createAt": "2016-02-25 18:09:48",
        "exhibitId": 0,
        "goodTimes": 0,
        "id": 7443,
        "isHot": 0,
        "parentCommentId": 0,
        "parentId": 0,
        "replyTimes": 0,
        "topicId": 0,
        "topicType": 0,
        "userId": 9846,
        "userName": "洱海环绕",
        "userPic": "http://7xavon.com1.z0.glb.clouddn.com/Frn5bVTu9yQyHg5UyLR0Adi6PV36",
        "verifyStatus": 0,
        "workId": 0
      }
    ],
    "hotTopicList": [
      {
        "author": "情况不明啦啦啦啦啦啦啦啦啦啦",
        "columnId": 1,
        "createAt": "2016-03-15 11:58:41",
        "curiosityPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FrjUrJSXyvcCyS8F5ZsEskKAbB4y",
        "id": 155,
        "isDeleted": 0,
        "isEnterfor": 0,
        "topicHeadType": 0,
        "topicLabel": "设计",
        "topicLabelId": 2,
        "topicName": "阿斯顿发送到发",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/Fp3-H_uXzLgLOHP7DghgNhxDuNS1",
        "topicType": 4,
        "userId": 9816,
        "viewerNum": 1547
      },
      {
        "columnId": 1,
        "createAt": "2016-02-24 18:17:34",
        "curiosityPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fknt5wCMshqEXDyUwwQbbE7dBMXP",
        "id": 138,
        "isDeleted": 0,
        "isEnterfor": 0,
        "scourceTable": "topic",
        "topicHeadType": 0,
        "topicLabel": "艺趣",
        "topicName": "GIF动画掀起了葛饰北斋的巨浪",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/FvFZFN7NFdiMDO6cIPWEC-BcKkUA",
        "topicType": 4,
        "viewerNum": 2056
      },
      {
        "author": "情况不明啦啦啦啦啦啦啦啦啦啦",
        "columnId": 1,
        "createAt": "2016-02-02 17:12:01",
        "curiosityPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FiqiIr98Hf6xaavQoGBEQr09QMda",
        "id": 129,
        "isDeleted": 0,
        "isEnterfor": 0,
        "scourceTable": "topic",
        "topicHeadType": 0,
        "topicLabel": "艺术",
        "topicLabelId": 1,
        "topicName": "玻璃海洋：凝固的波涛汹涌而来",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/Fp3fsdpOXsn1Z9r0fot3A1Bm3AAd",
        "topicType": 4,
        "userId": 9816,
        "viewerNum": 1891
      }
    ],
    "topic": {
      "columnId": 1,
      "createAt": "2016-02-24 18:17:34",
      "curiosityPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fknt5wCMshqEXDyUwwQbbE7dBMXP",
      "id": 138,
      "isDeleted": 0,
      "isEnterfor": 0,
      "joinNum": 0,
      "marketingDeschtml": "<p style=\"line-height: 1.5em;\">\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-\r\n\r\nscale=1.0, user-scalable=yes\"/><style>img{width:100%;}  p{letter-\r\n\r\nspacing:1px;padding:0 20px;word-break:break-all;}</style>\r\n    <title>\r\n        艺术狗-GIF动画掀起了葛饰北斋的巨浪\r\n    </title>\r\n</p>\r\n<p style=\"line-height: 1.75em;\">\r\n    <img src=\"http://7xavon.com1.z0.glb.clouddn.com/FhVvtMBjxF6hPY__IoiCOOSCb--E\"/>\r\n</p>\r\n<p style=\"line-height: 1.75em;\">\r\n    <span style=\"font-family: 微软雅黑, &#39;Microsoft YaHei&#39;; font-size: 14px; color: rgb(63, 63, 63);\">浮世绘是静态的，定格了一个充满戏剧感的瞬间，旧时人们看浮世绘一定会浮生各种想象。然而放到现在，要让这些刻板的画作动起来还不容易？日本一位名为<span style=\"font-family: 微软雅黑, &#39;Microsoft YaHei&#39;; font-size: 14px;\">Segawa&nbsp;37（濑川三十七）的动画制作人，便将这些经典的浮世绘名作加以重制，以GIF动画的形式让画作动了起来。</span></span>\r\n</p>\r\n<p style=\"text-align: center;line-height:30px;\">\r\n    <img src=\"http://7xavon.com1.z0.glb.clouddn.com/FkAW6oyZ6WZZIzIoo4bON_GZAsy2\" style=\"\"/><br/><span style=\"font-family: SourceHanSansCN-Regular; color: rgb(127, 127, 127); font-size: 12px;\">原作为葛饰北斋《神奈川巨浪》</span>\r\n</p>\r\n<p style=\"line-height: 1.75em;\">\r\n    <span style=\"font-family: 微软雅黑, &#39;Microsoft YaHei&#39;; font-size: 14px; color: rgb(63, 63, 63);\">浮世绘是日本的一种绘画艺术的形式，兴起于江户时代。浮世绘的英文译作“pictures&nbsp;of&nbsp;the&nbsp;floating&nbsp;world”，其字面意思是“虚浮世界的绘画”，描绘的是日本人生活的日常、风景与戏剧，更有很大一部分作画的题材与娼妓、赤裸的女性有关，因此在很长一段时间里浮世绘总被人们和春宫图关联在一起。</span>\r\n</p>\r\n<p style=\"text-align: center;line-height:30px;\">\r\n    <img src=\"http://7xavon.com1.z0.glb.clouddn.com/Fr6KYSUdOWqC8UyH_SaaMwDgwE_2\" style=\"\"/><br/><span style=\"font-family: SourceHanSansCN-Regular; color: rgb(127, 127, 127); font-size: 12px;\">原作为葛饰北斋《东海道吉田》</span>\r\n</p>\r\n<p style=\"line-height: 1.75em;\">\r\n    <span style=\"font-family: 微软雅黑, &#39;Microsoft YaHei&#39;; font-size: 14px; color: rgb(63, 63, 63);\">浮世绘通常被认为专指彩色印刷的木版画，但在其初期与发展过程中亦存在很多直接手绘的作品。日本浮世绘代表画师众多，如葛饰北斋、歌川国芳、月冈芳年等，他们的画作不仅在日本艺术史上着墨厚重，更在19世纪随日本的茶品出口，影响了众多欧洲画家。</span>\r\n</p>\r\n<p style=\"text-align: center;line-height:30px;\">\r\n    <img src=\"http://7xavon.com1.z0.glb.clouddn.com/FuVKketOdSDzosea-FyRDtmm9S5U\" style=\"\"/><br/><span style=\"font-family: SourceHanSansCN-Regular; color: rgb(127, 127, 127); font-size: 12px;\">原作为葛饰北斋《江都駿河町三井見世略図》</span>\r\n</p>\r\n<p style=\"line-height: 1.75em;\">\r\n    <span style=\"font-family: 微软雅黑, &#39;Microsoft YaHei&#39;; font-size: 14px; color: rgb(63, 63, 63);\">《江户百景》、《神奈川冲浪里》、《富岳三十六景》等著名画作流传至今，已然如同图腾一般常见。关于浮世绘足以展开丰富的篇幅，在此就不作延伸。作为一种极具戏剧张力的绘画艺术类型，浮世绘在当下的文化视界中总是以不同形式得以传续甚至“重生”。</span>\r\n</p>\r\n<p style=\"text-align: center;line-height:30px;\">\r\n    <img src=\"http://7xavon.com1.z0.glb.clouddn.com/FmOC-tbw4AsqijgCaCOiasHK07_s\" style=\"\"/><br/><span style=\"font-family: SourceHanSansCN-Regular; color: rgb(127, 127, 127); font-size: 12px;\">原作为葛饰北斋《駿州江尻图》</span>\r\n</p>\r\n<p style=\"line-height: 1.75em;\">\r\n    <span style=\"font-family: 微软雅黑, &#39;Microsoft YaHei&#39;; font-size: 14px; color: rgb(63, 63, 63);\">日本的浮世绘画家，首推葛饰北斋。他的绘画风格对后来的欧洲画坛影响很大，德加、马奈、梵高、高更等许多印象派绘画大师都临摹过他的作品。他还是入选“千禧年影响世界的一百位名人”中的唯一的一位日本人。</span>\r\n</p>\r\n<p style=\"text-align: center;line-height:30px;\">\r\n    <img src=\"http://7xavon.com1.z0.glb.clouddn.com/Fsj70KKiQ_aWvtQipQsdCh2fPyTl\" style=\"\"/><br/><span style=\"font-family: SourceHanSansCN-Regular; color: rgb(127, 127, 127); font-size: 12px;\">原作为葛饰北斋《富士三十六景》之一</span>\r\n</p>\r\n<p style=\"line-height: 1.75em;\">\r\n    <span style=\"font-family: 微软雅黑, &#39;Microsoft YaHei&#39;; font-size: 14px; color: rgb(63, 63, 63);\">在大胆吸收荷兰风景版画手法的同时，葛饰北斋又继承日本名胜画的传统，细心观察江户市民的生活风俗，结合西方手法和日本情趣创立的新样式代表作，出人意料的构图、或瞬间即逝的千姿百态，呈现出令人目眩的丰富表情。</span>\r\n</p>\r\n<p style=\"text-align: center;line-height:30px;\">\r\n    <img src=\"http://7xavon.com1.z0.glb.clouddn.com/FuThS2oHzvX7qqoOLYS6EcjhTk38\" style=\"\"/><br/><span style=\"font-family: SourceHanSansCN-Regular; color: rgb(127, 127, 127); font-size: 12px;\">原作为葛饰北斋《富士三十六景》之二</span>\r\n</p>\r\n<p style=\"line-height: 1.75em;\">\r\n    <img src=\"http://7xavon.com1.z0.glb.clouddn.com/FrWyLmruZVkSvmtEKYhS1SaStLcj\" title=\"\" alt=\"\"/>\r\n</p>",
      "showTopicHead": "1",
      "topicHeadType": 3,
      "topicLabelDefine": "美好,生活爱好,杂志",
      "topicName": "GIF动画掀起了葛饰北斋的巨浪",
      "topicType": 0,
      "viewerNum": 0
    }
  },
  "message": "请求成功",
  "status": "200"
}
