{
  "data": {
    "address": "上海市浦东新区罗山路2255弄210号(近花木路)",
    "attention": false,
    "attentionTimes": 217,
    "cityName": "上海",
    "collection": false,
    "createAt": "2015-04-30 22:56:06",
    "employeeId": 0,
    "exhibitNum": 0,
    "galleryDesc": "http://bm.artgoer.cn/list/e5fa3190-ee24-11e4-b226-c5429399ce3b.html",
    "galleryName": "龙美术馆",
    "galleryPic": "http://7xavon.com1.z0.glb.clouddn.com/FveqKokcof5J1lx3qF9PbLFqPF7A",
    "id": 1,
    "isRecommend": "1",
    "status": "0",
    "telNo": "021-68778787",
    "topics": [
      {
        "author": "情况不明啦啦啦啦啦啦啦啦啦啦",
        "columnId": 1,
        "createAt": "2016-03-15 15:19:39",
        "curiosityPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FqqxNQsUv9jL6XlZo9yT5bUdhV15",
        "id": 159,
        "isDeleted": 0,
        "isEnterfor": 0,
        "topicHeadType": 0,
        "topicLabel": "艺术",
        "topicLabelId": 1,
        "topicName": "杜拉斯，一个“情场高手”的自我修养",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/Fr-WaNL18s2DC7Vy__XfE6riXXXC",
        "topicType": 4,
        "userId": 9816,
        "viewerNum": 2095
      },
      {
        "author": "情况不明啦啦啦啦啦啦啦啦啦啦",
        "columnId": 1,
        "createAt": "2016-03-15 11:58:41",
        "curiosityPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FrjUrJSXyvcCyS8F5ZsEskKAbB4y",
        "id": 155,
        "isDeleted": 0,
        "isEnterfor": 0,
        "topicHeadType": 0,
        "topicLabel": "设计",
        "topicLabelId": 2,
        "topicName": "阿斯顿发送到发",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/Fp3-H_uXzLgLOHP7DghgNhxDuNS1",
        "topicType": 4,
        "userId": 9816,
        "viewerNum": 1547
      },
      {
        "columnId": 1,
        "createAt": "2016-02-24 18:17:34",
        "curiosityPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/Fknt5wCMshqEXDyUwwQbbE7dBMXP",
        "id": 138,
        "isDeleted": 0,
        "isEnterfor": 0,
        "scourceTable": "topic",
        "topicHeadType": 0,
        "topicLabel": "艺趣",
        "topicName": "GIF动画掀起了葛饰北斋的巨浪",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/FvFZFN7NFdiMDO6cIPWEC-BcKkUA",
        "topicType": 4,
        "viewerNum": 2056
      },
      {
        "author": "情况不明啦啦啦啦啦啦啦啦啦啦",
        "columnId": 1,
        "createAt": "2016-02-02 17:12:01",
        "curiosityPicUrl": "http://7xavon.com1.z0.glb.clouddn.com/FiqiIr98Hf6xaavQoGBEQr09QMda",
        "id": 129,
        "isDeleted": 0,
        "isEnterfor": 0,
        "scourceTable": "topic",
        "topicHeadType": 0,
        "topicLabel": "艺术",
        "topicLabelId": 1,
        "topicName": "玻璃海洋：凝固的波涛汹涌而来",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/Fp3fsdpOXsn1Z9r0fot3A1Bm3AAd",
        "topicType": 4,
        "userId": 9816,
        "viewerNum": 1891
      },
      {
        "columnId": 1,
        "createAt": "2015-12-07 10:25:10",
        "id": 67,
        "isDeleted": 0,
        "isEnterfor": 0,
        "scourceTable": "topic",
        "topicHeadType": 0,
        "topicLabelId": 3,
        "topicName": "abasdjksdbjk",
        "topicPic": "https://dn-ycaopan.qbox.me/t015ba9606549f3941c.jpg",
        "topicType": 4,
        "viewerNum": 167
      },
      {
        "author": "穆克良",
        "columnId": 1,
        "id": 683,
        "isDeleted": 0,
        "isEnterfor": 0,
        "scourceTable": "exhibit_works",
        "topicHeadType": 0,
        "topicLabel": "好的",
        "topicName": "好的",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/FnuWJrfJiD7YsIcHph-Stc8z0BeE",
        "topicType": 4,
        "userId": 1,
        "viewerNum": 0
      },
      {
        "author": "ddddd",
        "columnId": 1,
        "id": 192,
        "isDeleted": 0,
        "isEnterfor": 0,
        "scourceTable": "exhibits",
        "topicHeadType": 0,
        "topicLabel": "龙美术馆",
        "topicName": "伦勃朗的时代",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/exhibit32_work1.JPG",
        "topicType": 4,
        "userId": 43,
        "viewerNum": 0
      },
      {
        "author": "ddddd",
        "columnId": 1,
        "id": 249,
        "isDeleted": 0,
        "isEnterfor": 0,
        "scourceTable": "exhibits",
        "topicHeadType": 0,
        "topicLabel": "龙美术馆",
        "topicName": "何所示：丁乙个展",
        "topicPic": "http://7xavon.com1.z0.glb.clouddn.com/exhibit92__work1.jpg",
        "topicType": 4,
        "userId": 43,
        "viewerNum": 0
      }
    ],
    "workNum": 0
  },
  "message": "请求成功",
  "status": "200"
}
